pb_migrations/1742113297_created_news.js, pb_migrations/1742113502_updated_news.js
- **feat: add news refering changing standards**
- **fix: news can be draft**
=> fix: news can be in draft status

Makefile, pkg/gen.go
=> chore: use `go generate` to generate the config files

pkg/internal/pb/namespaces.go, pkg/internal/pb/workflow.go
- **fix: if namespace already exist dont create it**
- **fix: rely only on HookNamespaceOrgs to create new namespaces**
=> fix: if namespace already exist do not try to create a new one"

Makefile
Makefile:
"make doc" now uses --host
=> feat: make doc now --host

pb_migrations/1685000002_seed_features.js
=> Deactivate `DID` and `keypairoom` features

Makefile, Procfile, Procfile.dev, pkg/routes/routes.go
=> fix: log just on DEBUG. remove temporal-ui proxies

schemas/openid-credential-issuer.schema.json
from the https://www.iana.org/assignments/jose/jose.xhtml
=> fix: JSON Web Signature and Encryption Algorithms

webapp/src/modules/components/ui-custom/EudiwLogs.svelte
=> fix: fix firefox signal to eudiw poll log workflows

pkg/internal/apis/shared.go, pkg/internal/apis/workflows.go
- **fix: when superuser logs an organization was created**
=> fix: when superuser logs an organization was created

webapp/src/routes/(public)/organizations/+page.svelte
- **feat: in organizations page show only organizations with published entities**
close: #295
=> feat: in organizations page show only organizations with published entities

webapp/src/routes/(public)/organizations/+page.svelte
- **fix: organiztions page missing icons**
close: #297
=> fix: organiztions page missing logos

pb_migrations/1748297190_updated_users.js, webapp/messages/en.json, webapp/src/modules/utils/toUserTimezone.ts, webapp/src/routes/my/profile/_partials/userData.svelte, webapp/src/routes/my/tests/runs/+page.svelte, webapp/src/routes/my/tests/runs/[workflow_id]/[run_id]/components/temporal-workflow.svelte
- **fix: remove piselletto**
- **feat: user timezone**
close: #234 
close: #235
=> feat: user timezone

.dockerignore, .gitignore, webapp/messages/en.json, webapp/src/lib/layout/footer.svelte, webapp/src/routes/(public)/[...slug]/markdown-renderer.svelte, webapp/static/pages/conformance-automation/en.md
- Introduce a new markdown page explaining Conformance Automation, detailing its benefits and use cases for digital identity compliance.
- Add a link to the Conformance Automation page in the footer navigation.
- Enhance markdown-renderer styles to improve heading appearance.
- Update .gitignore and .dockerignore to include environment files.
- Clean up unused imports in footer component for better maintainability.
=> feat: add Conformance Automation page and update UI

webapp/src/lib/layout/newsCard.svelte, webapp/src/lib/types/openid-credential-issuer.ts, webapp/src/routes/(public)/news/+page.svelte
Updates the news card to include the date and time.
Also improves the styling of the card.
=> feat(news): improve news card layout

webapp/src/routes/my/services-and-products/_credentials/credential-issuer-section.svelte, webapp/src/routes/my/services-and-products/_verifiers/verifiers-section.svelte, webapp/src/routes/my/services-and-products/_wallets/wallets-section.svelte
=> fix: product and services order

webapp/src/app.html
=> feat: add matomo tracking code

webapp/src/lib/start-checks-form/configure-checks-form/configure-checks-form.svelte.ts
- **feat: filter checks runs by status (#403)**
- **chore(release): 🚀 update VERSION to 1.65.0**
- **chore(deps): bump github.com/go-viper/mapstructure/v2 (#414)**
- **fix: images not showing correctly in the markeplace (#442)**
- **chore(release): 🚀 update VERSION to 1.65.1**
- **fix: show default deeplink on empty field (#443)**
- **chore(release): 🚀 update VERSION to 1.65.2**
- **feat: refresh workflow UI (#444)**
- **chore(release): 🚀 update VERSION to 1.66.0**
- **chore: update docs and .env.example (#446)**
- **fix: use case verfication formatting (#449)**
- **chore(release): 🚀 update VERSION to 1.66.1**
- **fix: verifier image not showing (#452)**
- **chore(release): 🚀 update VERSION to 1.66.2**
- **fix: make site fully responsive (#445)**
- **chore(release): 🚀 update VERSION to …
=> fix missing fields name error

webapp/messages/en.json, webapp/src/routes/my/profile/+page.svelte
**NOTE: cannot edit email:**
```
PATCH http://127.0.0.1:8090/api/collections/users/records/14n41h5b276cx72 400 (Bad Request)
{
"data": {
"email": {
"code": "validation_values_mismatch",
"message": "Values don't match."
}
},
"message": "Failed to update record.",
"status": 400
}
```
=> feat: profile view for direct editing

webapp/src/routes/(public)/marketplace/(common)/verifiers/[verifier_id]/+page.svelte
=> fix: Safer description format missing.

pkg/internal/apis/handlers/templates_handlers.go, pkg/internal/apis/templating_test.go, pkg/internal/apis/workflows_test.go, pkg/internal/middlewares/validation_test.go
Now running `go test ./...`  from root make sense
=> fix: some go tests and remove old ones

webapp/src/modules/collections-components/manager/table/collectionTable.svelte, webapp/src/modules/components/ui/table/table.svelte, webapp/src/routes/(public)/marketplace/+page.svelte, webapp/src/routes/(public)/marketplace/_utils/marketplace-table.svelte, webapp/src/routes/(public)/marketplace/_utils/table-issuer-row-after.svelte, webapp/src/routes/(public)/marketplace/_utils/table-row-after.svelte, webapp/src/routes/(public)/marketplace/_utils/utils.ts
LMK
https://github.com/user-attachments/assets/9730204e-936d-4ed4-89ff-75aa068d449e
=> feat: add credentials dropdown in marketplace table

pb_migrations/1759326382_updated_marketplace_items.js, webapp/src/routes/(public)/marketplace/+page.svelte, webapp/src/routes/(public)/marketplace/_utils/marketplace-table.svelte, webapp/src/routes/(public)/marketplace/_utils/table-row-after.svelte, webapp/src/routes/(public)/marketplace/_utils/utils.ts
- Faster `credentials` and `verification_use_case` loading
- Fixed `cards` not showing
=> feat: improve marketplace table

.pre-commit-config.yaml, webapp/bun.lock, webapp/package.json, webapp/src/modules/collections-components/form/collectionForm.svelte, webapp/src/modules/collections-components/manager/collectionManager.svelte, webapp/src/modules/collections-components/manager/record-actions/recordCreate.svelte, webapp/src/modules/collections-components/manager/record-actions/recordDelete.svelte, webapp/src/modules/collections-components/manager/record-actions/recordEdit.svelte, webapp/src/modules/forms/fields/codeEditorField.svelte, webapp/src/routes/my/services-and-products/_credentials/deeplink-tabs/dynamic-tab.svelte
Update `node_modules` after doing this!
=> chore: fix eslint warnings
